import type { CocktailItem } from "./type";

const items: CocktailItem[] = [
    {
        id: "negroni",
        name: "네그로니",
        baseSpirit: "진",
        style: "비터·스티어드",
        abvFeel: "중간",
        servingGlass: "올드패션드 글라스",
        highlightIngredients: "캄파리, 스위트 베르무트",
        priceKrw: 16000,
        currencyLabel: "₩",
        servingUnit: "잔",
        soldOut: false,
        summary:
            "진·캄파리·스위트 베르무트의 쓴맛과 허브향의 균형. 애피타이저 전에 어울림.",
        mixersNote: "캄파리, 스위트 베르무트",
        temperatureNote: "차갑게, 스티어드",
        ingredientList: ["진", "캄파리", "스위트 베르무트"],
        abvPercent: "약 24% (매장 기준)",
        pairingTags: ["지방 적은 튀김과"],
    },
    {
        id: "old-fashioned",
        name: "올드 패션드",
        baseSpirit: "버번/라이 위스키",
        style: "스티어드·숏 드링크",
        abvFeel: "높음",
        servingGlass: "올드패션드 글라스",
        highlightIngredients: "설탕 시럽, 비터",
        priceKrw: 18000,
        currencyLabel: "₩",
        servingUnit: "잔",
        soldOut: false,
        summary:
            "설탕과 비터로 위스키의 단맛과 향을 끌어올린 클래식. 천천히 마시기 좋음.",
        mixersNote: "설탕, 비터, 워터 소량",
        temperatureNote: "차갑게, 큐브 아이스",
        pairingTags: ["스테이크류"],
    },
    {
        id: "margarita",
        name: "마가리타",
        baseSpirit: "테킬라",
        style: "사워·마가리타 글라스",
        abvFeel: "중간",
        servingGlass: "마가리타 글라스",
        highlightIngredients: "라임, 오렌지 리큐르",
        priceKrw: 15000,
        currencyLabel: "₩",
        servingUnit: "잔",
        soldOut: false,
        summary:
            "테킬라·라임·오렌지 리큐르의 산미와 짠 림. 멕시코 요리와 잘 맞음.",
        mixersNote: "라임, 오렌지 리큐르, 삼바이",
        temperatureNote: "차갑게, 셰이크",
        pairingTags: ["멕시코 요리"],
    },
    {
        id: "mojito",
        name: "모히토",
        baseSpirit: "화이트 럼",
        style: "하이볼·민트",
        abvFeel: "낮음–중간",
        servingGlass: "하이볼 글라스",
        highlightIngredients: "민트, 라임, 소다",
        priceKrw: 14000,
        currencyLabel: "₩",
        servingUnit: "잔",
        soldOut: true,
        summary:
            "민트·라임·소다의 청량감. 알코올 감은 상대적으로 부드러운 편.",
        mixersNote: "화이트 럼, 민트, 라임, 소다",
        temperatureNote: "차갑게, 크러시드 아이스",
        storeComment: "시즌 한정 민트 재고 확인 중",
    },
    {
        id: "whiskey-sour",
        name: "위스키 사워",
        baseSpirit: "위스키",
        style: "사워·프로티 폼 옵션",
        abvFeel: "중간",
        servingGlass: "쿠페 또는 롱 글라스",
        highlightIngredients: "시트러스, 설탕",
        priceKrw: 17000,
        currencyLabel: "₩",
        servingUnit: "잔",
        soldOut: false,
        summary:
            "시트러스 사워와 위스키 바디의 조합. 상큼하게 시작해 깊은 여운.",
        mixersNote: "레몬, 설탕 시럽, (옵션) 에그 화이트",
        temperatureNote: "차갑게, 셰이크",
    },
    {
        id: "gin-tonic",
        name: "진 토닉",
        baseSpirit: "진",
        style: "하이볼",
        abvFeel: "낮음–중간",
        servingGlass: "하이볼 글라스",
        highlightIngredients: "토닉, 라임",
        priceKrw: 13000,
        currencyLabel: "₩",
        servingUnit: "잔",
        soldOut: false,
        summary:
            "진의 보태니컬과 토닉의 퀴닌 쓴맛. 장시간 마시기 쉬운 표준 하이볼.",
        mixersNote: "토닉, 라임 웨지",
        temperatureNote: "차갑게, 하이볼",
    },
];

export function getItems(): CocktailItem[] {
    return items;
}
