import type { WineItem } from "./type";

const items: WineItem[] = [
    {
        id: "bordeaux-left",
        name: "보르도 좌안 블렌드 (예시 라벨)",
        wineType: "레드",
        varietal: "카베르네 소비뇽 중심",
        region: "프랑스",
        bodyTag: "높음",
        acidTag: "중간",
        tanninTag: "높음",
        vintageLabel: "2018",
        priceGlassKrw: 18000,
        priceBottleKrw: 98000,
        currencyLabel: "₩",
        soldOutGlass: false,
        soldOutBottle: false,
        tastingNose: "블랙커런트, 시더, 연필 샤프니스.",
        tastingPalate: "타닌과 구조감, 긴 여운.",
        tastingFinish: "스파이스와 오크 톤이 이어짐.",
        pairing: "스테이크·양념 강한 육류",
        serveTemp: "약간 시원하게(16–18°C)",
        decanting: "optional",
        abv: "13.5%",
    },
    {
        id: "burgundy-chard",
        name: "부르고뉴 샤르도네 마을급 (예시)",
        wineType: "화이트",
        varietal: "샤르도네",
        region: "프랑스",
        bodyTag: "중간",
        acidTag: "높음",
        tanninTag: "낮음",
        vintageLabel: "2020",
        priceGlassKrw: 22000,
        priceBottleKrw: 110000,
        currencyLabel: "₩",
        soldOutGlass: false,
        soldOutBottle: false,
        tastingNose: "시트러스, 흰 꽃, 젖은 돌 미네랄.",
        tastingPalate: "산도가 선명하고 질감이 촘촘.",
        tastingFinish: "미네랄리한 마무리.",
        pairing: "해산물, 크림 소스 요리",
        serveTemp: "10–12°C",
        decanting: "no",
        abv: "13%",
    },
    {
        id: "chianti-classico",
        name: "이탈리아 키안티 클래식 (예시)",
        wineType: "레드",
        varietal: "산지오베제",
        region: "이탈리아",
        bodyTag: "중간",
        acidTag: "높음",
        tanninTag: "중간",
        vintageLabel: "2019",
        priceGlassKrw: 16000,
        priceBottleKrw: null,
        currencyLabel: "₩",
        soldOutGlass: true,
        soldOutBottle: false,
        tastingNose: "체리, 건허브, 토마토 잎.",
        tastingPalate: "산도와 과실의 균형.",
        tastingFinish: "허브와 산미가 남는 마무리.",
        pairing: "토마토 파스타, 얇게 썬 프로슈토",
        decanting: "optional",
    },
    {
        id: "prosecco",
        name: "스파클링 프로세코 (예시)",
        wineType: "스파클링",
        varietal: "글레라",
        region: "이탈리아 베네토",
        bodyTag: "낮음–중간",
        acidTag: "중간",
        tanninTag: "낮음",
        vintageLabel: "NV",
        priceGlassKrw: 12000,
        priceBottleKrw: 45000,
        currencyLabel: "₩",
        soldOutGlass: false,
        soldOutBottle: false,
        tastingNose: "사과·배, 흰 꽃, 가벼운 거품.",
        tastingPalate: "청량한 산미와 과실.",
        tastingFinish: "짧고 깔끔.",
        pairing: "에피타이저, 가벼운 전채",
        serveTemp: "6–8°C",
        decanting: "no",
        abv: "11%",
    },
    {
        id: "napa-cab",
        name: "나파 밸리 카베르네 (예시)",
        wineType: "레드",
        varietal: "카베르네 소비뇽",
        region: "미국",
        bodyTag: "높음",
        acidTag: "중간",
        tanninTag: "중간–높음",
        vintageLabel: "2017",
        priceGlassKrw: null,
        priceBottleKrw: 145000,
        currencyLabel: "₩",
        soldOutGlass: false,
        soldOutBottle: false,
        tastingNose: "블랙커런트, 바닐라, 토스트 오크.",
        tastingPalate: "풍만한 바디와 익은 과실.",
        tastingFinish: "스파이스와 오크가 길게 이어짐.",
        pairing: "그릴드 립아이, 강한 치즈",
        serveTemp: "16–18°C",
        decanting: "yes",
        abv: "14.5%",
    },
];

export function getItems(): WineItem[] {
    return items;
}
