import type { WhiskyItem } from "./type";

const items: WhiskyItem[] = [
    {
        id: "glenlivet-12",
        name: "Glenlivet 12yo (예시)",
        category: "스카치 싱글 몰트",
        regionStyle: "스페이사이드",
        agingCask: "버번·셰리 캐스크 블렌드",
        abv: "40%",
        servingUnit: "30ml",
        priceKrw: 19000,
        currencyLabel: "₩",
        soldOut: false,
        regionBlurb:
            "과일·꽃향이 비교적 부드럽고 입문자에게 무난한 스페이사이드 감을 기대할 수 있는 스타일입니다.",
        tastingNose: "사과·배 같은 밝은 과실.",
        tastingPalate: "부드러운 당도와 가벼운 바디.",
        tastingFinish: "짧고 깔끔한 마무리.",
        drinkingStyles: "스트레이트, 온더록, 하이볼",
        serveTempNote: "약간 냉각 또는 실온",
        distilleryNote: "스페이사이드 대표 증류소 라인업(매장 카피 기준).",
    },
    {
        id: "laphroaig-10",
        name: "Laphroaig 10yo (예시)",
        category: "스카치 싱글 몰트",
        regionStyle: "아일라·페이티드",
        agingCask: "버번 캐스크",
        abv: "40%",
        servingUnit: "30ml",
        priceKrw: 21000,
        currencyLabel: "₩",
        soldOut: false,
        regionBlurb:
            "요오드·메디컬한 스모크가 강한 것으로 널리 알려진 아일라 대표 스타일입니다.",
        tastingNose: "스모크·메디컬, 이오딘 힌트.",
        tastingPalate: "짭짤함과 피트, 캠프파이어 감.",
        tastingFinish: "길고 스모키한 여운.",
        drinkingStyles: "소량 워터, 온더록",
        caskDetail: "전통적인 버번 캐스크 숙성 표기(예시).",
    },
    {
        id: "yamazaki-dr",
        name: "Yamazaki Distiller’s Reserve (예시)",
        category: "재패니즈 위스키",
        regionStyle: "일본",
        agingCask: "다양한 캐스크(미즈나라 힌트 언급 가능)",
        abv: "43%",
        servingUnit: "30ml",
        priceKrw: 28000,
        currencyLabel: "₩",
        soldOut: false,
        regionBlurb:
            "일본 증류소에서 나오는 과실·미즈나라 오크 힌트가 언급되는 제품군(매장 카피에 맞춤).",
        tastingNose: "과실·스파이스.",
        tastingPalate: "단맛과 스파이스의 균형.",
        tastingFinish: "오크 감이 잔존하는 중간 길이.",
        drinkingStyles: "스트레이트 추천",
    },
    {
        id: "buffalo-trace",
        name: "Buffalo Trace (예시)",
        category: "버번",
        regionStyle: "켄터키",
        agingCask: "신규 참나무 통 숙성",
        abv: "45%",
        servingUnit: "45ml",
        priceKrw: 16000,
        currencyLabel: "₩",
        soldOut: true,
        regionBlurb:
            "옥통 숙성 버번으로 알려진 바디감과 바닐라·캐러멜 톤이 흔한 설명입니다.",
        tastingNose: "바닐라·캐러멜, 옥통 스위트니스.",
        tastingPalate: "달콤함과 스파이스, 코코넛 힌트.",
        tastingFinish: "중간 길이의 스파이시 마무리.",
        drinkingStyles: "온더록, 클래식 버번 칵테일 베이스",
        storeComment: "입고 지연으로 일시 품절(예시)",
    },
    {
        id: "redbreast-12",
        name: "Redbreast 12yo (예시)",
        category: "아이리시 포트 스틸",
        regionStyle: "아일랜드",
        agingCask: "셰리 캐스크",
        abv: "40%",
        servingUnit: "30ml",
        priceKrw: 22000,
        currencyLabel: "₩",
        soldOut: false,
        regionBlurb:
            "아이리시 싱글 포트 스틸의 부드러운 질감·셰리 캐스크 단말이 자주 언급됩니다.",
        tastingNose: "건과일·스파이스.",
        tastingPalate: "크리미한 질감과 셰리 단말.",
        tastingFinish: "달콤한 여운.",
        drinkingStyles: "스트레이트, 소량 워터",
    },
];

export function getItems(): WhiskyItem[] {
    return items;
}
